import profile from './assets/profs.JPG';
import googlepic from './assets/googleps.jpg';
import speaker from './assets/speak.jpg';
import IOTpic from './assets/IOT.jpeg';
import solvento from './assets/cropped-Spi-logo-2048x547.png';
import kadakareer from './assets/kadakareer.png';
import makati from './assets/makati-logo.png';
import v88 from "./assets/village_88_logo.jpeg";
import tac from './assets/tacpic.jpg';
import outlier from './assets/outlier.jpeg';
import './App.css';
import React, { useState } from 'react';
import {
  FaBars,
  FaTimes,
  FaGithub,
  FaLinkedin,
  FaFacebook,
  FaLinkedinIn,
} from 'react-icons/fa';
import { HiOutlineMail } from 'react-icons/hi';
import { BsFillPersonLinesFill } from 'react-icons/bs';

function HomePage() {
  const certifications = [
    {
      id: 1,
      name: 'Microsoft Azure Fundamentals',
      image: 'link-to-your-azure-badge-image', // Replace with actual image URL
      link: 'https://example.com/certificate-1', // Replace with actual certificate URL
    },
    {
      id: 2,
      name: 'AWS Certified Cloud Practitioner',
      image: 'link-to-your-aws-badge-image', // Replace with actual image URL
      link: 'https://example.com/certificate-2', // Replace with actual certificate URL
    },
    {
      id: 3,
      name: 'Google Cloud Associate Engineer',
      image: 'link-to-your-google-cloud-badge-image', // Replace with actual image URL
      link: 'https://example.com/certificate-3', // Replace with actual certificate URL
    },
    // Add more certifications as needed
  ];
  const projectData = [
    {
      company: 'Solvento Philippines, Inc.',
      role: 'System Engineer',
      date: 'Feb 2024 - Present',
      location: 'Makati City',
      description: 'E-commerce platform built with modern web technologies...',
      imageUrl: solvento,
    },
    {
      company: 'Outlier',
      role: 'Freelance Code AI Trainer',
      date: 'Oct 2024 - Present',
      location: 'Remote - San Francisco, US',
      description: 'Crafting and answering questions related to computer science in order to help train AI models. Evaluating and ranking code generated by AI models',
      imageUrl: outlier,
    },
    {
      company: 'Upwork',
      role: 'Freelance Web and Application Dev',
      date: 'Aug 2024 - Present',
      location: 'Remote - San Francisco, US',
      description: '• Developed and maintained custom web and mobile applications for clients, ensuring high performance, user-friendly interfaces, and cross-platform compatibility.',
      imageUrl: 'https://cdn.builder.io/api/v1/image/assets/TEMP/92134e0a3d91264fa5930deee4a7507472fa055e17e22acfc4e2b24032304535?',
    },
    {
      company: 'Kadakareer',
      role: 'Product Engineer',
      date: 'Jan 2024 - June 2024',
      location: 'Manila',
      description: '• Enhancing existing products (Koach Konnector and Kareer Explorer) with new features and updates. • Developed new products to add to in platform. • Utilized frameworks like React, NodeJS, ExpressJS and Firebase to create scalable and responsive web applications.',
      imageUrl: kadakareer,
    },
    {
      company: 'Village 88',
      role: 'Full Stack Web Development Trainee',
      date: 'Jan 2024 - June 2024',
      location: 'Manila',
      description: '• Created various website using Javascript and PHP',
      imageUrl: v88,
    },
    {
      company: 'Barangay Hall',
      role: 'IT Support OJT',
      date: 'Aug 2023 - Dec 2023',
      location: 'Pembo, Makati City ',
      description: 'I ensure that the data is accurate and organized. I efficiently managed large datasets, adhering to established formats and procedures to maintain data integrity.',
      imageUrl: makati,
    },
    {
      company: 'Makati City Hall',
      role: 'IT Support OJT',
      date: 'Jan 2021 - March 2020',
      location: 'Makati City ',
      description: 'I ensure that the data is accurate and organized in Local Civil Registry Department. I efficiently managed large datasets, adhering to established formats and procedures to maintain data integrity.',
      imageUrl: v88,
    },
    {
      company: 'Tori Anime Collectibles',
      role: 'Business owner',
      date: 'Jan 2021 - Feb 2023',
      location: 'Makati City ',
      description: 'Importing action figure from suppliers in Japan and selling here in Philippines.',
      imageUrl: tac,
    },
  ];

  const educationData = [
    {
      company: 'Upwork',
      role: 'Freelance Web and Mobile Developer',
      date: 'Jan 2024 - June 2024',
      description: 'Boost your productivity with this to-do app...',
      imageUrl: profile,
    },
    {
      company: 'Solvento',
      role: 'System Engineer',
      date: 'Jan 2024 - June 2024',
      description: 'E-commerce platform built with modern web technologies...',
      imageUrl: 'https://cdn.builder.io/api/v1/image/assets/TEMP/92134e0a3d91264fa5930deee4a7507472fa055e17e22acfc4e2b24032304535?',
    },
    {
      company: 'Kadakareer',
      role: 'Product Engineer',
      date: 'Jan 2024 - June 2024',
      description: 'A mobile-first responsive blog application...',
      imageUrl: 'https://cdn.builder.io/api/v1/image/assets/TEMP/92134e0a3d91264fa5930deee4a7507472fa055e17e22acfc4e2b24032304535?',
    },
  ];

  const [hoveredCard, setHoveredCard] = useState(null);

  const cardsData = [
    { id: 1, title: 'App Name', description: 'Lorem ipsum dolor sit amet...' },
    { id: 2, title: 'App Name', description: 'Lorem ipsum dolor sit amet...' },
    { id: 3, title: 'App Name', description: 'Lorem ipsum dolor sit amet...' },
  ];

  const handleMouseEnter = (id) => {
    setHoveredCard(id);
  };

  const handleMouseLeave = () => {
    setHoveredCard(null);
  };


  return (
    <div className="bg-gradient-to-b from-black to-purple-600 min-h-screen text-white font-sans">

      {/* Navbar */}
      <nav className="flex justify-between items-center p-6">
        <div className="text-2xl font-bold">DevEzi</div>
          <ul className="hidden md:flex space-x-6">
            <a href="#home" className="hover:text-purple-400 transition-colors duration-300">
              Home
            </a>
            <a href="#projects" className="hover:text-purple-400 transition-colors duration-300">
              Projects
            </a>
            <a href="#about" className="hover:text-purple-400 transition-colors duration-300">
              About
            </a>
            <a href="#contact" className="hover:text-purple-400 transition-colors duration-300">
              Contact
            </a>
          </ul>
          <div className="md:hidden">
            {/* Mobile Menu Button (you can add functionality to toggle a mobile menu here) */}
            <button className="text-white">Menu</button>
          </div>
      </nav>

      {/* Hero Section */}
      <section className="flex flex-col items-center justify-center h-screen text-center animate__animated animate__fadeIn">
        <h1 className="text-6xl font-bold animate__animated animate__bounceInDown">
          Hi! I'm <span className="text-purple-500">DEV EZI</span>
        </h1>
        <p className="mt-4 text-lg animate__animated animate__fadeInUp">Full Stack Developer</p>
        <button className="mt-8 px-8 py-3 bg-purple-600 rounded-full text-white hover:bg-purple-700 transition duration-300 animate__animated animate__pulse">
          Contact Me
        </button>
      </section>



      {/* About Section */}
      <section id="about" className="p-10 bg-purple-900">
        <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
          {/* Left Side - Images */}
          <div className="grid grid-cols-2 gap-4">
            <img src={profile} alt="Profilepic" className="rounded-lg w-full" />
            <img src={googlepic} alt="At Google" className="rounded-lg w-full" />
            <img src={speaker} alt="Public Speaking" className="rounded-lg w-full" />
            <img src={IOTpic} alt="Working on a project" className="rounded-lg w-full" />
            
          </div>

          {/* Right Side - About Me Text */}
          <div className="text-white">
            <h2 className="text-4xl font-bold mb-4">ABOUT ME</h2>
            <h3 className="text-3xl font-bold text-purple-400 mb-4">Hi there! I’m Ezekielle Gambong.</h3>
            <p className="text-lg leading-relaxed mb-4">
              I’m a full stack developer committed to creating web applications that elevate user experiences. Demonstrating a strong aptitude for how front-end looks and back-end functionality.
            </p>
            <p className="text-lg leading-relaxed">
              I do more than just coding. Systems engineering is something I'm very interested in. My curiosity extends to understanding the architecture and infrastructure that support applications. I ensure that the applications I create not only function flawlessly but are also supported by well-designed, resilient systems.
            </p>
          </div>
        </div>
      </section>

      {/* Tech Stack Section */}
      <div className="bg-gradient-to-b from-purple-900 to-black py-12 px-4">
        <div className="max-w-6xl mx-auto text-center">
          <h2 className="text-3xl font-bold text-white mb-6">MY TECH STACK</h2>
    
          {/* Tech Stack Grid */}
          <div className="grid grid-cols-3 md:grid-cols-8 gap-8 items-center">
            <div className="opacity-70 hover:opacity-100 transition duration-300">
              <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/ae1ac3d0b8f742ea388396233a0fc2fac722c2521bc16662a80f1e77d551833c?" alt="JavaScript" className="w-16 mx-auto"/>
            </div>
            <div className="opacity-70 hover:opacity-100 transition duration-300">
              <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/a2577ef3e1131864b3d5bbb1894317fc821ea4cc1cad5fa757d7470484f21e15?" alt="React" className="w-16 mx-auto"/>
            </div>
            <div className="opacity-70 hover:opacity-100 transition duration-300">
              <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/cdbf70f3b182e880a85a00006614768a76b0efae8312a56536c205b7f41196fc?" alt="NodeJs" className="w-16 mx-auto"/>
            </div>
            <div className="opacity-70 hover:opacity-100 transition duration-300">
              <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/37362dec13330eae26b614d6a3379edd5cbaf7790e5634795915003b3072a389?" alt="ExpressJs" className="w-16 mx-auto"/>
            </div>
            <div className="opacity-70 hover:opacity-100 transition duration-300">
              <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/958267494732001c9c932bec3a487935cd7381de3e0dd18846f929e855ba6826?" alt="MongoDB" className="w-16 mx-auto"/>
            </div>
            <div className="opacity-70 hover:opacity-100 transition duration-300">
              <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/a65b205db44e70558956d1e8f5e5092f78cc44862e5bccc02ce25d8096a25c78?" alt="Tailwind" className="w-16 mx-auto"/>
            </div>
            <div className="opacity-70 hover:opacity-100 transition duration-300">
              <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/6375e1b5920c21551f8b2117ef965682d7038a987f9ce9af2105e80963335220?" alt="Figma" className="w-16 mx-auto"/>
            </div>
            <div className="opacity-70 hover:opacity-100 transition duration-300">
              <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/c96ba05ff8fda2036be5e0b89b0de15c0837e16a77174847f2d8bca462dfab94?" alt="Git" className="w-16 mx-auto"/>
            </div>
          </div>
        </div>
      </div>


      {/* Experience Section */}
      <div className="px-6 py-12 bg-black text-white">
        {/* Grid layout for both sections */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          {/* Professional Experience Section */}
          <section>
            <h2 className="text-3xl font-bold text-center lg:text-left">Professional Experience</h2>
            <p className="mt-2 text-lg text-center lg:text-left text-gray-400">
              Here are some of my work experiences.
            </p>
            <div className="mt-8 grid gap-6">
              {projectData.map((project, index) => (
                <div
                  key={index}
                  className="p-6 bg-gray-800 rounded-lg shadow-lg transition duration-300 ease-in-out transform hover:scale-105 
                            hover:bg-gradient-to-r hover:from-purple-500 hover:to-indigo-500"
                >
                  <div className="flex justify-between mb-2">
                    <h3 className="text-xl font-semibold">{project.role}</h3>
                    <h4 className="text-sm">{project.date}</h4>
                  </div>
                  <div className="flex  items-center mb-4 space-x-4 ">
                    <span className="bg-indigo-600 text-white px-2 py-1 rounded-md text-sm">{project.company}</span>
                    <span className="bg-indigo-600 text-white px-2 py-1 rounded-md text-sm">{project.location}</span>
                    <img
                      src={project.imageUrl}
                      alt={project.company}
                      className="self-start max-w-full aspect-[3.7] w-[102px]"
                    />
                  </div>
                  <p className="text-gray-400">{project.description}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Educational Background Section */}
          <section>
            <h2 className="text-3xl font-bold text-center lg:text-left">Educational Background</h2>
            <div className="mt-8 grid gap-6">
              {educationData.map((education, index) => (
                <div
                  key={index}
                  className="p-6 bg-gray-800 rounded-lg shadow-lg transition duration-300 ease-in-out transform hover:scale-105 
                            hover:bg-gradient-to-r hover:from-green-400 hover:to-blue-500"
                >
                  <h3 className="text-xl font-semibold mb-2">{education.degree}</h3>
                  <h4 className="text-m font-semibold">{education.school}</h4>
                  <h4 className="text-m font-semibold">{education.location}</h4>
                  <p className="text-m text-gray-400">{education.date}</p>
                  <p className="text-gray-400">{education.description}</p>
                </div>
              ))}
            </div>
          </section>
        </div>
      </div>

      
      {/* Projects */}
      <div className="flex justify-center items-center h-screen bg-gradient-to-b from-black to-purple-900 min-h-screen">
        <div className="flex space-x-4">
          {cardsData.map((card) => (
            <div
              key={card.id}
              onMouseEnter={() => handleMouseEnter(card.id)}
              onMouseLeave={handleMouseLeave}
              className={`transition-all duration-300 ease-in-out transform rounded-xl p-6 bg-gray-800 text-center ${
                hoveredCard === card.id ? 'scale-110' : 'scale-100'
              } ${hoveredCard === null || hoveredCard === card.id ? 'opacity-100' : 'opacity-70'}`}
              style={{ width: hoveredCard === card.id ? '350px' : '300px', height: '400px' }}
            >
              <h3 className="text-lg font-semibold text-gray-300 uppercase">Tagline</h3>
              <h2 className="text-3xl font-bold text-white mt-2">{card.title}</h2>
              <p className="text-gray-400 mt-4">{card.description}</p>
              <button className="mt-6 px-4 py-2 bg-purple-600 text-white rounded-full hover:bg-purple-700">
                See more
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Social icons */}
      <div className="hidden lg:flex fixed flex-col bottom-0 left-0 mb-4">
        <ul>
          {/* LinkedIn Icon */}
          <li className="w-[160px] h-[60px] flex justify-between items-center ml-[-100px] hover:ml-[-10px] duration-300 bg-blue-600">
            <a
              className="flex justify-between items-center w-full text-gray-300"
              href="https://www.linkedin.com"
              target="_blank"
              rel="noreferrer"
            >
              LinkedIn <FaLinkedin size={30} />
            </a>
          </li>

          {/* GitHub Icon */}
          <li className="w-[160px] h-[60px] flex justify-between items-center ml-[-100px] hover:ml-[-10px] duration-300 bg-[#333333]">
            <a
              className="flex justify-between items-center w-full text-gray-300"
              href="https://github.com"
              target="_blank"
              rel="noreferrer"
            >
              GitHub <FaGithub size={30} />
            </a>
          </li>

          {/* Email Icon */}
          <li className="w-[160px] h-[60px] flex justify-between items-center ml-[-100px] hover:ml-[-10px] duration-300 bg-[#6fc2b0]">
            <a
              className="flex justify-between items-center w-full text-gray-300"
              href="mailto:someone@example.com"
            >
              Email <HiOutlineMail size={30} />
            </a>
          </li>

          {/* Resume Icon */}
          <li className="w-[160px] h-[60px] flex justify-between items-center ml-[-100px] hover:ml-[-10px] duration-300 bg-[#565f69]">
            <a
              className="flex justify-between items-center w-full text-gray-300"
              href="/resume.pdf"
              target="_blank"
              rel="noreferrer"
            >
              Resume <BsFillPersonLinesFill size={30} />
            </a>
          </li>
        </ul>
      </div>

      {/* <section className="bg-[#1e1e2e] py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-4xl font-bold text-white mb-8">My Certifications</h2>
          <div className="flex flex-wrap justify-center items-center space-x-6">
            {certifications.map((cert) => (
              <a
                key={cert.id}
                href={cert.link}
                target="_blank"
                rel="noopener noreferrer"
                className="transition-transform transform hover:scale-110"
              >
                <img
                  src={cert.image}
                  alt={cert.name}
                  className="w-32 h-32 object-contain mx-auto mb-4"
                />
                <p className="text-lg text-gray-300">{cert.name}</p>
              </a>
            ))}
          </div>
        </div>
      </section> */}

      {/* Footer */}
      <footer className="p-6 text-center bg-purple-900">
        <p>&copy; 2024 DevEzi. All rights reserved.</p>
      </footer>
    </div>
  );
}

export default HomePage;
